apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: pm-digital-twin
build:
  artifacts:
    - image: iteam1337/pm-digital-twin-simulation-engine
      context: packages/simulator
    - image: iteam1337/pm-digital-twin-visualisation
      context: packages/visualisation
      docker:
        buildArgs:
          REACT_APP_MAPBOX_ACCESS_TOKEN: "{{.REACT_APP_MAPBOX_ACCESS_TOKEN}}"
          REACT_APP_SIMULATOR_URL: https://rorla-engine.predictivemovement.se
deploy:
  kustomize:
    paths:
      - k8s/base
  statusCheckDeadlineSeconds: 600
profiles:
- name: prod
  deploy:
    kustomize:
      paths:
      - k8s/overlays/prod
  build:
    artifacts:
    - image: iteam1337/pm-digital-twin-simulation-engine
      context: packages/simulator
    - image: iteam1337/pm-digital-twin-visualisation
      context: packages/visualisation
      docker:
        buildArgs:
          REACT_APP_MAPBOX_ACCESS_TOKEN: "{{.REACT_APP_MAPBOX_ACCESS_TOKEN}}"
          REACT_APP_SIMULATOR_URL: https://rorla-engine.predictivemovement.se
- name: staging
  deploy:
    kustomize:
      paths:
      - k8s/overlays/staging
  build:
    artifacts:
    - image: iteam1337/pm-digital-twin-simulation-engine
      context: packages/simulator
    - image: iteam1337/pm-digital-twin-visualisation
      context: packages/visualisation
      docker:
        buildArgs:
          REACT_APP_MAPBOX_ACCESS_TOKEN: "{{.REACT_APP_MAPBOX_ACCESS_TOKEN}}"
          REACT_APP_SIMULATOR_URL: https://rorla-engine-stage.predictivemovement.se