apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: pm-digital-twin
build:
  artifacts:
    - image: iteam1337/pm-digital-twin-simulation-engine
      context: packages/simulator
    - image: iteam1337/pm-digital-twin-visualisation
      context: packages/visualisation
      docker:
        buildArgs:
          REACT_APP_MAPBOX_ACCESS_TOKEN: "{{.REACT_APP_MAPBOX_ACCESS_TOKEN}}" # these needs to be set at build time
          REACT_APP_SIMULATOR_URL: "/" 
deploy:
  kustomize:
    paths:
      - k8s/base
      # uncomment these if you want to install the dependencies
      #- k8s/dependencies
  statusCheckDeadlineSeconds: 600
profiles:
- name: prod
  activation:
    - env: GITHUB_REF_TYPE=tag
  deploy:
    kustomize:
      paths:
      - k8s/overlays/prod
- name: staging
  deploy:
    kustomize:
      paths:
      - k8s/overlays/staging