apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
spec:
  tls:
    - hosts:
        - kibana.iteam.services
        - kibana.predictivemovement.se
      secretName: kibana-prod-tls
  rules:
    - host: kibana.iteam.services
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana
                port:
                  number: 5601
    - host: kibana.predictivemovement.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana
                port:
                  number: 5601
