apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simulator-ingress
spec:
  tls:
    - hosts:
        - rorla-engine.predictivemovement.se
      secretName: simulator-prod-tls
  rules:
    - host: rorla-engine.predictivemovement.se