apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simulator-ingress-helsingborg
spec:
  tls:
    - hosts:
        - tvilling.predictivemovement.se
        - helsingborg.predictivemovement.se # Legacy.
        - rorla.predictivemovement.se # Legacy.
      secretName: helsingborg-prod-tls
  rules:
    - host: tvilling.predictivemovement.se
      http:
        paths:
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: simulator
                port:
                  number: 4000
    - host: helsingborg.predictivemovement.se
      http:
        paths:
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: simulator
                port:
                  number: 4000
    - host: rorla.predictivemovement.se
      http:
        paths:
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: simulator
                port:
                  number: 4000
