## These only include lines we want to replace
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: visualisation-ingress
spec:
  tls:
    - hosts:
        - rorla.predictivemovement.se
      secretName: visualisation-prod-tls
  rules:
    - host: rorla.predictivemovement.se
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualisation
spec:
  selector:
    matchLabels:
      app: visualisation
  template:
    spec:
      containers:
        - name: visualisation
          env:
            - name: REACT_APP_SIMULATOR_URL
              value: https://rorla-engine.predictivemovement.se