apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: visualisation-ingress
spec:
  tls:
    - hosts:
        - tvilling.predictivemovement.se
        - helsingborg.predictivemovement.se # Legacy.
        - rorla.predictivemovement.se # Legacy.
      secretName: digital-twin-prod-tls # Legacy.
  rules:
    - host: tvilling.predictivemovement.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: visualisation
                port:
                  number: 80
    - host: helsingborg.predictivemovement.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: visualisation
                port:
                  number: 80
    - host: rorla.predictivemovement.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: visualisation
                port:
                  number: 80
