## These only include lines we want to replace
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: visualisation-ingress
spec:
  tls:
    - hosts:
        - rorla.iteam.services
        - rorla.predictivemovement.se
      secretName: rorla-prod-tls
  rules:
    - host: rorla.iteam.services
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: visualisation
                port:
                  number: 80
    - host: rorla.predictivemovement.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: visualisation
                port:
                  number: 80