apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helsingborg
#nameSuffix: -prod

patchesStrategicMerge:
  - visualisation.yaml
  - simulator.yaml

resources:
  - ../../../base
