# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
  - simulator.yaml
  - visualisation.yaml

# namespace to deploy all Resources to main namespace
namespace: digital-twin
