apiVersion: v1
kind: Service
metadata:
  name: simulation-engine
spec:
  ports:
    - port: 4000
      targetPort: 4000
  type: LoadBalancer
  selector:
    app: simulation-engine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation-engine
spec:
  selector:
    matchLabels:
      app: simulation-engine
  template:
    metadata:
      labels:
        app: simulation-engine
    spec:
      containers:
        - name: simulation-engine
          image: iteam1337/pm-digital-twin-simulation-engine
          ports:
            - containerPort: 4000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simulation-engine-ingress
  annotations:
    kubernetes.io/ingress.class: "public"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - digital-twin-engine.iteamdev.io
      secretName: simulation-engine-prod-tls
  rules:
    - host: digital-twin-engine.iteamdev.io
      http:
        paths:
          - backend:
              serviceName: simulation-engine
              servicePort: 4000
