apiVersion: v1
kind: Service
metadata:
  name: visualisation
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: visualisation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualisation
spec:
  selector:
    matchLabels:
      app: visualisation
  template:
    metadata:
      labels:
        app: visualisation
    spec:
      containers:
        - name: visualisation
          image: iteam1337/pm-digital-twin-visualisation
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_SIMULATOR_URL
              value: https://drone-engine.predictivemovement.se
          #   - name: REACT_APP_MAPBOX_ACCESS_TOKEN
          #     valueFrom:
          #       secretKeyRef:
          #         key: REACT_APP_MAPBOX_ACCESS_TOKEN
          #         name: mapbox-access-tokens
           
              
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: visualisation-ingress
  annotations:
    kubernetes.io/ingress.class: "public"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - drone.predictivemovement.se
      secretName: visualisation-prod-tls
  rules:
    - host: drone.predictivemovement.se
      http:
        paths:
          - backend:
              serviceName: visualisation
              servicePort: 80
