apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: $KUBE_CLUSTER_CERTIFICATE
      server: $KUBE_CLUSTER_SERVER
    name: default
contexts:
  - context:
      cluster: default
      user: default
    name: default
kind: Config
preferences: {}
users:
  - name: default
    user:
      token: $KUBE_USER_TOKEN
