apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helsingborg

resources:
- ../../base/digital-twin

patches:
- path: visualisation.yaml
- path: simulator.yaml
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: REGIONS
        value: "skane"
    - op: replace
      path: /spec/template/spec/containers/0/env/-
      value:
        name: TRAFIKLAB_KEY
        value: "4ca25c172513453da871ee9d044544f1"
  target:
    kind: Deployment
    name: simulator