apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simulator-ingress
spec:
  tls:
    - hosts:
        - helsingborg.telge.iteam.pub # Legacy.
      secretName: helsingborg-prod-tls
  rules:
    - host: helsingborg.telge.iteam.pub
      http:
        paths:
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: simulator
                port:
                  number: 4000
