---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
spec:
  selector: 
    matchLabels:
      app: simulator
  template:
    spec:
      containers:
        - name: simulator
          env:
            - name: TRAFIKLAB_KEY
              value: 4ca25c172513453da871ee9d044544f1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simulator-ingress
spec:
  tls:
    - hosts:
        - helsingborg.predictivemovement.se # Legacy.
      secretName: helsingborg-prod-tls
  rules:
    - host: helsingborg.predictivemovement.se
      http:
        paths:
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: simulator
                port:
                  number: 4000
